### ISSUE TITLE
Hi，I want ask some questions about screentime

### ISSUE THREAD

**Issue by yutangChina** [TernovoiD/ScreenTime-ios#1]
Hello, I am a beginner in Swift. I am currently trying to develop an iOS application using Screen Time. However, I am having difficulty understanding the relationship between family controls, manage settings, and device activity, as well as the specific order in which they are executed. Could you please assist me with this?thanks.

**Comment by yutangChina** [comment]
Thank you for your reply; it's very helpful to me. 
I have another question: are the data in 'managesettings' permanent?

**Comment by TernovoiD** [comment]
Your setup of ManagedSettingsStore() is permanent. Adding applications, web domains and categories to shield will be saved event between app launchings. Moreover, these settings are shared between your application and extensions, so you can add shields in the app and remove shields in DeviceActivityMonitor Extension.

You can also create up to 50 of your own ManagedSettingStore accessible from everywhere. Changing settings in one managed store will not interact with settings in another managed store: 
        * ManagedSettingsStore(named: "gaming")
        * ManagedSettingsStore(named: "socialNetworks")
        * ManagedSettingsStore(named: "userSelected")
     
Highly recommend watching WWDC Screen Time API videos from Apple

**Comment by yutangChina** [comment]
thank you!
